name: Clang Format

on:
  pull_request:
    types: [labeled]

jobs:
  format:
    if: ${{ github.event.label.name == 'format' }}
    name: Format code with clang-format
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Get .clang-format from origin/main
        run: |
          git fetch origin ${{ github.event.repository.default_branch }}
          git checkout origin/${{ github.event.repository.default_branch }} -- .clang-format

      - name: Set up clang-format
        run: sudo apt-get install -y clang-format

      - name: Run clang-format
        run: |
          find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\|c\|h\)' -exec clang-format -style=file -i {} \;

      - name: Get diff
        id: diff
        run: |
          git diff --numstat > changes.txt
          ADDED=$(awk '{sum += $1} END {print (sum == 0 ? 0 : sum)}' changes.txt || echo 0)
          DELETED=$(awk '{sum += $2} END {print (sum == 0 ? 0 : sum)}' changes.txt || echo 0)
          FILES=$(wc -l < changes.txt)
          echo "ADDED=$ADDED" >> $GITHUB_OUTPUT
          echo "DELETED=$DELETED" >> $GITHUB_OUTPUT
          echo "FILES=$FILES" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3
        with:
          commit_message: "style: apply clang-format [bot]"
          add_options: '-u'

      - name: Print result
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ✅ Format completed
            ```diff
            + ${{ steps.diff.outputs.ADDED }} lines added
            - ${{ steps.diff.outputs.DELETED }} lines removed
            Edited: ${{ steps.diff.outputs.FILES }} files
            ```
