name: Clang Format

on:
  pull_request:
    types: [labeled]

jobs:
  format:
    if: ${{ github.event.label.name == 'format' }}
    name: Format code with clang-format
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Get .clang-format from origin/main
        run: |
          git fetch origin main
          git checkout origin/main -- .clang-format

      - name: Set up clang-format
        run: sudo apt-get install -y clang-format

      - name: Run clang-format
        run: |
          find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\|c\|h\)' -exec clang-format -style=file -i {} \;

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403
        with:
          commit_message: "style: apply clang-format [bot]"
          add_options: '-u'
