on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@0f58ae7c5036094a1e3e750d18772af92821b503
      with:
        extra_args: --results=verified,unknown
