on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@a05cf0859455b5b16317ee22d809887a4043cdf0
      with:
        extra_args: --results=verified,unknown
