name: Clang Format Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  typos:
    name: Finds and corrects spelling mistakes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: typos-action
        uses: crate-ci/typos@v1.32.0
