name: Typos Check

permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CLICOLOR: 1

jobs:
  spelling:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v4
    - name: Spell Check Repo
      uses: crate-ci/typos@v1.32.0
      with:
        config: .github/typos.toml
